Restore cors
eva-gallery/backend pull request #9
Opened 2024-11-15 17:40 UTC by dudo50

Endpoints didn't work without cors. Restore cors temporarily.

2024-11-15 17:40 UTC, dudo50 commented
cc @Teebor-Choka

2024-11-15 20:54 UTC, Teebor-Choka requested changes

2024-11-15 20:54 UTC, Teebor-Choka commented on src/main.ts
> +    origin: config.get("FRONTEND_URL"),
This should be `origin: *`. Backend should not know about the frontend url.

2024-11-16 07:44 UTC, dudo50 commented
cc @Teebor-Choka

2024-11-16 22:00 UTC, merged